receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
  zabbixreceiver:
    endpoint: 0.0.0.0:54319
processors:
  batch:

exporters:
  debug:
    verbosity: detailed

service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [debug]
    metrics:
      receivers: [zabbixreceiver,otlp]
      processors: [batch]
      exporters: [debug]
  telemetry:
    logs:
      level: debug
